CREATE TABLE article(
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT  '文章id',
  `content` TEXT NOT NULL COMMENT '文章内容',
  PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8 COMMENT='文章表';